//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public int Id { get; set; }
        public string characterName { get; set; }
        public string audio { get; set; }
        public string photograph { get; set; }
    
        public virtual Board Board { get; set; }
    }
}
